### ISSUE TITLE
Shows yellow for any amount of a single character entered

### ISSUE THREAD

**Issue by RossSmyth** [Keftcha/sha256le#1]
For example if I type in 64 "A" they will all by yellow. But there are not 64 A's in the sha256. To follow Wordle convention there should only be as many yellow tiles as there are that character in the sequence. Then the rest should be black or whatever color is chosen as not being in the sequence.
![image](https://user-images.githubusercontent.com/18294397/155839278-93d7723d-f14c-4084-87cd-32d0aa9e9faa.png)

**Comment by Keftcha** [comment]
Thanks, it seems to be corrected.
![image](https://user-images.githubusercontent.com/39836656/155852010-8ac9d9b0-1ba1-45a9-9253-4b416bc7026d.png)

**Comment by 229c9cf0** [comment]
@Keftcha looks like an off-by-one or something like that:

![image](https://user-images.githubusercontent.com/44428570/155858407-deefd194-1329-453b-81d7-27f67b1647a5.png)

![image](https://user-images.githubusercontent.com/44428570/155858397-08befe3d-74d7-4116-afe7-d678faeab361.png)

And from the way things are going...

![image](https://user-images.githubusercontent.com/44428570/155858419-ab98e6ce-e15c-494e-bbd8-9a1f3b11acae.png)

...I suspect *all* are counted at one too few.
